/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import controller.*;
import javax.swing.ButtonGroup;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author Lenovo
 */
public class GUIAdmin extends javax.swing.JFrame {
    
    private ControllerMainMenu ctrlMM;
    private ControllerAdmin ctrlAdm;
    private Application model;
    
    public GUIAdmin(ControllerMainMenu ctrlMM, Application model) {
        initComponents();
        this.ctrlMM = ctrlMM;
        ctrlAdm = new ControllerAdmin(model, this);
        this.model = model;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJKTG = new javax.swing.ButtonGroup();
        tpAdmin = new javax.swing.JTabbedPane();
        pTourGuide = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbLakiTG = new javax.swing.JRadioButton();
        rbPerempuanTG = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnInputTG = new javax.swing.JButton();
        spTbViewTGTG = new javax.swing.JScrollPane();
        tbViewTGTG = new javax.swing.JTable();
        tfIdTG = new javax.swing.JTextField();
        tfNamaTG = new javax.swing.JTextField();
        tfUmurTG = new javax.swing.JTextField();
        tfAlamatTG = new javax.swing.JTextField();
        tfKontakTG = new javax.swing.JTextField();
        pCustomer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbViewCs = new javax.swing.JTable();
        btnRefreshCs = new javax.swing.JButton();
        pRekapPemesanan = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbViewRP = new javax.swing.JTable();
        btnRefreshRP = new javax.swing.JButton();
        pTempatWisata = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbViewTW = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnInputTW = new javax.swing.JButton();
        slRatingInputTW = new javax.swing.JSlider();
        jLabel34 = new javax.swing.JLabel();
        tfIdInputTW = new javax.swing.JTextField();
        tfNamaInputTW = new javax.swing.JTextField();
        tfAlamatInputTW = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        btnEditTW = new javax.swing.JButton();
        btnSearchEditTW = new javax.swing.JButton();
        slRatingEditTW = new javax.swing.JSlider();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tfIdSearchEditTW = new javax.swing.JTextField();
        tfNamaEditTW = new javax.swing.JTextField();
        tfAlamatEditTW = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnSearchDeleteTW = new javax.swing.JButton();
        btnDeleteTW = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbViewDeleteTW = new javax.swing.JTable();
        tfIdSearchDeleteTW = new javax.swing.JTextField();
        pPaketWisata = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbViewPW = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnInputPW = new javax.swing.JButton();
        tfIdInputPW = new javax.swing.JTextField();
        tfNamaInputPW = new javax.swing.JTextField();
        tfHargaInputPW = new javax.swing.JTextField();
        tfTglBInputPW = new javax.swing.JTextField();
        tfTglPInputPW = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsTWInputPW = new javax.swing.JList<>();
        btnRefreshTWInputPW = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        lsTGInputPW = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnEditPW = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnSearchEditPW = new javax.swing.JButton();
        tfIdSearchEditPW = new javax.swing.JTextField();
        tfNamaEditPW = new javax.swing.JTextField();
        tfHargaEditPW = new javax.swing.JTextField();
        tfTglBEditPW = new javax.swing.JTextField();
        tfTglPEditPW = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        lsTWEditPW = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        lsTGEditPW = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnSearchDeletePW = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbViewDeletePW = new javax.swing.JTable();
        btnDeletePW = new javax.swing.JButton();
        tfIdSearchDeletePW = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBMM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(1000, 500));

        tpAdmin.setName("coba"); // NOI18N

        pTourGuide.setName(""); // NOI18N

        jLabel2.setText("Nama :");

        jLabel3.setText("ID :");

        bgJKTG.add(rbLakiTG);
        rbLakiTG.setText("Laki - Laki");
        rbLakiTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiTGActionPerformed(evt);
            }
        });

        bgJKTG.add(rbPerempuanTG);
        rbPerempuanTG.setText("Perempuan");
        rbPerempuanTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanTGActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Kelamin :");

        jLabel5.setText("Umur :");

        jLabel6.setText("Alamat :");

        jLabel7.setText("Kontak :");

        btnInputTG.setText("Input");
        btnInputTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputTGActionPerformed(evt);
            }
        });

        tbViewTGTG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Gender", "Umur", "Alamat", "Kontak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTbViewTGTG.setViewportView(tbViewTGTG);

        tfIdTG.setEditable(false);

        javax.swing.GroupLayout pTourGuideLayout = new javax.swing.GroupLayout(pTourGuide);
        pTourGuide.setLayout(pTourGuideLayout);
        pTourGuideLayout.setHorizontalGroup(
            pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTourGuideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInputTG)
                    .addGroup(pTourGuideLayout.createSequentialGroup()
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(55, 55, 55)
                        .addComponent(tfIdTG, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTourGuideLayout.createSequentialGroup()
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNamaTG)
                            .addGroup(pTourGuideLayout.createSequentialGroup()
                                .addComponent(rbLakiTG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPerempuanTG))
                            .addComponent(tfUmurTG)
                            .addComponent(tfAlamatTG)
                            .addComponent(tfKontakTG, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(spTbViewTGTG, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pTourGuideLayout.setVerticalGroup(
            pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTourGuideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTbViewTGTG, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pTourGuideLayout.createSequentialGroup()
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNamaTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbLakiTG)
                            .addComponent(rbPerempuanTG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfUmurTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfAlamatTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfKontakTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btnInputTG)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tpAdmin.addTab("TOUR GUIDE", pTourGuide);

        pCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCustomerMouseClicked(evt);
            }
        });

        tbViewCs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Gender", "Umur", "Alamat", "Kontak"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbViewCs);

        btnRefreshCs.setText("Refresh");
        btnRefreshCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCustomerLayout = new javax.swing.GroupLayout(pCustomer);
        pCustomer.setLayout(pCustomerLayout);
        pCustomerLayout.setHorizontalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
                    .addGroup(pCustomerLayout.createSequentialGroup()
                        .addComponent(btnRefreshCs)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pCustomerLayout.setVerticalGroup(
            pCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshCs)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        tpAdmin.addTab("CUSTOMER", pCustomer);

        tbViewRP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pemesanan", "Customer", "Paket Wisata", "Tanggal Pesan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbViewRP);

        btnRefreshRP.setText("Refresh");
        btnRefreshRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshRPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRekapPemesananLayout = new javax.swing.GroupLayout(pRekapPemesanan);
        pRekapPemesanan.setLayout(pRekapPemesananLayout);
        pRekapPemesananLayout.setHorizontalGroup(
            pRekapPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRekapPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRekapPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
                    .addGroup(pRekapPemesananLayout.createSequentialGroup()
                        .addComponent(btnRefreshRP)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pRekapPemesananLayout.setVerticalGroup(
            pRekapPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRekapPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefreshRP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpAdmin.addTab("REKAP PEMESANAN", pRekapPemesanan);

        tbViewTW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbViewTW);

        jLabel21.setText("Nama :");

        jLabel23.setText("ID :");

        jLabel26.setText("Alamat :");

        btnInputTW.setText("Input");
        btnInputTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputTWActionPerformed(evt);
            }
        });

        jLabel34.setText("Rating :");

        tfIdInputTW.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel34))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfAlamatInputTW, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNamaInputTW, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdInputTW, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slRatingInputTW, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addComponent(btnInputTW))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIdInputTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfNamaInputTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfAlamatInputTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(slRatingInputTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)))
                .addComponent(btnInputTW)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Input", jPanel9);

        jLabel29.setText("Masukkan ID :");

        btnEditTW.setText("Edit Data");
        btnEditTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTWActionPerformed(evt);
            }
        });

        btnSearchEditTW.setText("Search");
        btnSearchEditTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEditTWActionPerformed(evt);
            }
        });

        jLabel35.setText("Rating :");

        jLabel36.setText("Alamat :");

        jLabel22.setText("Nama :");

        tfIdSearchEditTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdSearchEditTWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditTW)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel29))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slRatingEditTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfAlamatEditTW, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNamaEditTW, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(tfIdSearchEditTW, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSearchEditTW))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(tfIdSearchEditTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchEditTW))
                .addGap(39, 39, 39)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfNamaEditTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(tfAlamatEditTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slRatingEditTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addComponent(btnEditTW)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Edit Data", jPanel10);

        jLabel33.setText("Masukkan ID :");

        btnSearchDeleteTW.setText("Search");
        btnSearchDeleteTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDeleteTWActionPerformed(evt);
            }
        });

        btnDeleteTW.setText("Delete");
        btnDeleteTW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTWActionPerformed(evt);
            }
        });

        tbViewDeleteTW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "Rating"
            }
        ));
        jScrollPane7.setViewportView(tbViewDeleteTW);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(28, 28, 28)
                                .addComponent(tfIdSearchDeleteTW, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchDeleteTW))
                            .addComponent(btnDeleteTW))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(tfIdSearchDeleteTW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchDeleteTW))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDeleteTW)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Delete", jPanel11);

        javax.swing.GroupLayout pTempatWisataLayout = new javax.swing.GroupLayout(pTempatWisata);
        pTempatWisata.setLayout(pTempatWisataLayout);
        pTempatWisataLayout.setHorizontalGroup(
            pTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTempatWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pTempatWisataLayout.setVerticalGroup(
            pTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTempatWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane3))
                .addContainerGap())
        );

        tpAdmin.addTab("TEMPAT WISATA", pTempatWisata);

        tbViewPW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Harga", "List Tujuan", "List Guide", "Tanggal Berangkat", "Tanggal Pulang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbViewPW);
        if (tbViewPW.getColumnModel().getColumnCount() > 0) {
            tbViewPW.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbViewPW.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        jLabel8.setText("Nama :");

        jLabel12.setText("Tanggal Berangkat :");

        jLabel9.setText("ID :");

        jLabel13.setText("Tanggal Pulang :");

        jLabel14.setText("Tempat Wisata :");

        jLabel11.setText("Harga :");

        btnInputPW.setText("Input");
        btnInputPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPWActionPerformed(evt);
            }
        });

        tfIdInputPW.setEditable(false);

        jScrollPane1.setViewportView(lsTWInputPW);

        btnRefreshTWInputPW.setText("refresh");
        btnRefreshTWInputPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTWInputPWActionPerformed(evt);
            }
        });

        jLabel24.setText("Tour Guide :");

        jScrollPane9.setViewportView(lsTGInputPW);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnInputPW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshTWInputPW))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfNamaInputPW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfIdInputPW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfHargaInputPW, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTglBInputPW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(21, 21, 21)
                                .addComponent(tfTglPInputPW, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIdInputPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfNamaInputPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfHargaInputPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfTglBInputPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfTglPInputPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jScrollPane9))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInputPW)
                    .addComponent(btnRefreshTWInputPW))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Input", jPanel6);

        jLabel10.setText("Nama :");

        jLabel15.setText("Tanggal Berangkat :");

        jLabel16.setText("Masukkan ID :");

        jLabel17.setText("Tanggal Pulang :");

        btnEditPW.setText("Edit Data");
        btnEditPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPWActionPerformed(evt);
            }
        });

        jLabel18.setText("Tempat Wisata :");

        jLabel19.setText("Harga :");

        btnSearchEditPW.setText("Search");
        btnSearchEditPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEditPWActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(lsTWEditPW);

        jLabel25.setText("Tour Guide :");

        jScrollPane10.setViewportView(lsTGEditPW);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditPW)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(37, 37, 37)
                            .addComponent(tfTglPEditPW))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel16)
                                .addComponent(jLabel19)
                                .addComponent(jLabel15))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfTglBEditPW)
                                .addComponent(tfHargaEditPW)
                                .addComponent(tfNamaEditPW)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(tfIdSearchEditPW, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSearchEditPW))))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(tfIdSearchEditPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchEditPW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNamaEditPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfHargaEditPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfTglBEditPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfTglPEditPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jScrollPane10))
                .addGap(18, 18, 18)
                .addComponent(btnEditPW)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edit Data", jPanel7);

        jLabel20.setText("Masukkan ID :");

        btnSearchDeletePW.setText("Search");

        tbViewDeletePW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Gender", "Umur", "Alamat", "Kontak"
            }
        ));
        jScrollPane4.setViewportView(tbViewDeletePW);
        if (tbViewDeletePW.getColumnModel().getColumnCount() > 0) {
            tbViewDeletePW.getColumnModel().getColumn(3).setHeaderValue("Umur");
            tbViewDeletePW.getColumnModel().getColumn(4).setHeaderValue("Alamat");
            tbViewDeletePW.getColumnModel().getColumn(5).setHeaderValue("Kontak");
        }

        btnDeletePW.setText("Delete");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(29, 29, 29)
                        .addComponent(tfIdSearchDeletePW, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchDeletePW))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePW))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tfIdSearchDeletePW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchDeletePW))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDeletePW)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete", jPanel8);

        javax.swing.GroupLayout pPaketWisataLayout = new javax.swing.GroupLayout(pPaketWisata);
        pPaketWisata.setLayout(pPaketWisataLayout);
        pPaketWisataLayout.setHorizontalGroup(
            pPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPaketWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        pPaketWisataLayout.setVerticalGroup(
            pPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPaketWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpAdmin.addTab("PAKET WISATA", pPaketWisata);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu Admin");

        btnBMM.setText("Back to Main Menu");
        btnBMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpAdmin)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(299, 299, 299)
                        .addComponent(btnBMM)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBMM))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(tpAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 1016, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void rbLakiTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiTGActionPerformed

    private void rbPerempuanTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanTGActionPerformed

    private void btnInputTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputTGActionPerformed
        ctrlAdm.inputTG();
    }//GEN-LAST:event_btnInputTGActionPerformed

    private void btnInputPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPWActionPerformed
        ctrlAdm.inputPW();
    }//GEN-LAST:event_btnInputPWActionPerformed

    private void btnEditPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPWActionPerformed
        ctrlAdm.editPW();
    }//GEN-LAST:event_btnEditPWActionPerformed

    private void btnInputTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputTWActionPerformed
        ctrlAdm.inputTW();
    }//GEN-LAST:event_btnInputTWActionPerformed

    private void btnEditTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTWActionPerformed
        ctrlAdm.editTW();
    }//GEN-LAST:event_btnEditTWActionPerformed

    private void btnBMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMMActionPerformed
        ctrlMM.toMainMenu();
    }//GEN-LAST:event_btnBMMActionPerformed

    private void pCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCustomerMouseClicked

    }//GEN-LAST:event_pCustomerMouseClicked

    private void btnRefreshCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCsActionPerformed
        ctrlAdm.updateViewCs();
    }//GEN-LAST:event_btnRefreshCsActionPerformed

    private void btnRefreshRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshRPActionPerformed
        ctrlAdm.updateViewRP();
    }//GEN-LAST:event_btnRefreshRPActionPerformed

    private void tfIdSearchEditTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdSearchEditTWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdSearchEditTWActionPerformed

    private void btnSearchEditTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEditTWActionPerformed
        ctrlAdm.searchIdEditTW();
    }//GEN-LAST:event_btnSearchEditTWActionPerformed

    private void btnSearchDeleteTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDeleteTWActionPerformed
        ctrlAdm.searchIdDeleteTW();
    }//GEN-LAST:event_btnSearchDeleteTWActionPerformed

    private void btnDeleteTWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTWActionPerformed
        ctrlAdm.deleteTW();
    }//GEN-LAST:event_btnDeleteTWActionPerformed

    private void btnRefreshTWInputPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTWInputPWActionPerformed
        ctrlAdm.refreshTWInputPW();
        ctrlAdm.refreshTGinputPW();
    }//GEN-LAST:event_btnRefreshTWInputPWActionPerformed

    private void btnSearchEditPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEditPWActionPerformed
        ctrlAdm.searchIdEditPW();
    }//GEN-LAST:event_btnSearchEditPWActionPerformed

  
    
    //TOUR GUIDE
    //GETTER
    public JTextField getTfIdTG(){
        return tfIdTG;
    }
    public JTextField getTfNamaTG(){
        return tfNamaTG;
    }
    public ButtonGroup getBgJKTG(){
        return bgJKTG;
    }
    public String getRbJKTG(){
        if(rbLakiTG.isSelected()){
            return "Laki-Laki";
        }else{
            return "Perempuan";
        }
    }
    public JRadioButton getRbLakiTG(){
        return rbLakiTG;
    }
    public JRadioButton getRbPerempuanTG(){
        return rbPerempuanTG;
    }
    public JTextField getTfUmurTG(){
        return tfUmurTG;
    }
    public JTextField getTfAlamatTG(){
        return tfAlamatTG;
    }
    public JTextField getTfKontakTG(){
        return tfKontakTG;
    }
    public void resetViewTG(){
        tfIdTG.setText("TG-"+TourGuide.getSidTG());
        tfNamaTG.setText("");
        bgJKTG.clearSelection();
        tfUmurTG.setText("");
        tfAlamatTG.setText("");
        tfKontakTG.setText("");
        
        DefaultTableModel tbModel = (DefaultTableModel) tbViewTGTG.getModel();
        tbModel.setRowCount(0);
    }
    public void updateTableTG(){
        DefaultTableModel tbModel = (DefaultTableModel) tbViewTGTG.getModel();
        String[] row = new String[6];
        for(int j = 0; j<model.getDaftarTG().size(); j++){
            row[0] = model.getDaftarTG().get(j).getId();
            row[1] = model.getDaftarTG().get(j).getNama();
            row[2] = model.getDaftarTG().get(j).getJenisKelamin();
            row[3] = model.getDaftarTG().get(j).getUmur();
            row[4] = model.getDaftarTG().get(j).getAlamat();
            row[5] = model.getDaftarTG().get(j).getKontak();
            tbModel.addRow(row);           
        }
    }
    
    //CUSTOMER
    //GETTTER
    public JTable getTbViewCs(){
        return tbViewCs;
    }
    
    //REKAP PEMESANAN
    //GETTER
    public JTable getTbViewRP(){
        return tbViewRP;
    }
    
    //TEMPAT WISATA
    //INPUT
    public JTextField getTfIdInputTW(){
        return tfIdInputTW;
    }
    public JTextField getTfNamaInputTW(){
        return tfNamaInputTW;
    }
    public JTextField getTfAlamatInputTW(){
        return tfAlamatInputTW;
    }
    public JSlider getSlRatingInputTW(){
        return slRatingInputTW;
    }    
    //EDIT
    public JTextField getTfIdSearchEditTW(){
        return tfIdSearchEditTW;
    }
    public JTextField getTfNamaEditTW(){
        return tfNamaEditTW;
    }
    public JTextField getTfAlamatEditTW(){
        return tfAlamatEditTW;
    }
    public JSlider getSlRatingEditTW(){
        return slRatingEditTW;
    }    
    //DELETE
    public JTextField getTfIdSearchDeleteTW(){
        return tfIdSearchDeleteTW;
    }
    public JTable getTbViewDeleteTW(){
        return tbViewDeleteTW;
    }
    //VIEW
    public void resetViewInputTW(){
        tfIdInputTW.setText("TW-"+TempatWisata.getSidTW());
        tfNamaInputTW.setText("");
        tfAlamatInputTW.setText("");
        slRatingInputTW.setValue(0);
        DefaultTableModel tbModel = (DefaultTableModel) tbViewTW.getModel();
        tbModel.setRowCount(0);
    }
    public void resetViewEditTW(){
        tfIdSearchEditTW.setText("TW-"+TempatWisata.getSidTW());
        tfNamaEditTW.setText("");
        tfAlamatEditTW.setText("");
        slRatingEditTW.setValue(0);
        DefaultTableModel tbModel = (DefaultTableModel) tbViewTW.getModel();
        tbModel.setRowCount(0);
    }
    public void resetViewDeleteTW(){
        tfIdSearchDeleteTW.setText("");
        DefaultTableModel tbModelDel = (DefaultTableModel) tbViewDeleteTW.getModel();
        tbModelDel.setRowCount(0);
        DefaultTableModel tbModel = (DefaultTableModel) tbViewTW.getModel();
        tbModel.setRowCount(0);
    }
    public void updateTableTW(){
        DefaultTableModel tbModel = (DefaultTableModel) tbViewTW.getModel();
        String[] row = new String[4];
        for(int j = 0; j<model.getDaftarTW().size(); j++){
            row[0] = model.getDaftarTW().get(j).getId();
            row[1] = model.getDaftarTW().get(j).getNama();
            row[2] = model.getDaftarTW().get(j).getAlamat();
            row[3] = Integer.toString(model.getDaftarTW().get(j).getRating());
            tbModel.addRow(row);           
        }
    }
    
    //PAKET WISATA
    //INPUT
    public JTextField getTfIdInputPW(){
        return tfIdInputPW;
    }
    public JTextField getTfNamaInputPW(){
        return tfNamaInputPW;
    }
    public JTextField getTfHargaInputPW(){
        return tfHargaInputPW;
    }
    public JTextField getTfTglBInputPW(){
        return tfTglBInputPW;
    }
    public JTextField getTfTglPInputPW(){
        return tfTglPInputPW;
    }
    public JList getLsTWInputPW(){
        return lsTWInputPW;
    }
    public JList getLsTGInputPW(){
        return lsTGInputPW;
    }
    //EDIT
    public JTextField getTfIdSearchEditPW(){
        return tfIdSearchEditPW;
    }
    public JTextField getTfNamaEditPW(){
        return tfNamaEditPW;
    }
    public JTextField getTfHargaEditPW(){
        return tfHargaEditPW;
    }
    public JTextField getTfTglBEditPW(){
        return tfTglBEditPW;
    }
    public JTextField getTfTglPEditPW(){
        return tfTglPEditPW;
    }
    public JList getLsTWEditPW(){
        return lsTWEditPW;
    }
    public JList getLsTGEditPW(){
        return lsTGEditPW;
    }
    //DELETE
    public JTextField getTfIdSearchDeletePW(){
        return tfIdSearchDeletePW;
    }
    public JTable getTbViewDeletePW(){
        return tbViewDeletePW;
    }
    //VIEW
    public void resetViewInputPW(){
        tfIdInputPW.setText("PW-"+PaketWisata.getSidPW());
        tfNamaInputPW.setText("");
        tfHargaInputPW.setText("");
        tfTglBInputPW.setText("");
        tfTglPInputPW.setText("");
        lsTWInputPW.clearSelection();
        lsTGInputPW.clearSelection();
        DefaultTableModel tbModel = (DefaultTableModel) tbViewPW.getModel();
        tbModel.setRowCount(0);
    }
    public void resetViewEditPW(){
        tfIdSearchEditPW.setText("");
        tfNamaEditPW.setText("");
        tfHargaEditPW.setText("");
        tfTglBEditPW.setText("");
        tfTglPEditPW.setText("");
        lsTWEditPW.clearSelection();
        lsTGEditPW.clearSelection();
        DefaultTableModel tbModel = (DefaultTableModel) tbViewPW.getModel();
        tbModel.setRowCount(0);
    }
    public void resetViewDeletePW(){
        tfIdSearchDeletePW.setText("");
        DefaultTableModel tbModelDel = (DefaultTableModel) tbViewDeletePW.getModel();
        tbModelDel.setRowCount(0);
        DefaultTableModel tbModel = (DefaultTableModel) tbViewPW.getModel();
        tbModel.setRowCount(0);
    }
    public void updateTablePW(){
        DefaultTableModel tbModel = (DefaultTableModel) tbViewPW.getModel();
        String[] row = new String[7];
        for(int j = 0; j<model.getDaftarPW().size(); j++){
            row[0] = model.getDaftarPW().get(j).getId();
            row[1] = model.getDaftarPW().get(j).getNama();
            row[2] = Double.toString(model.getDaftarPW().get(j).getHarga());
            row[3] = "";
            for(TempatWisata tw: model.getDaftarPW().get(j).getListTujuan()){
                row[3] += tw.getNama()+", ";
            }
            row[4] = "";
            for(TourGuide tg: model.getDaftarPW().get(j).getListGuide()){
                row[4] += tg.getNama()+", ";
            }
            row[5] = model.getDaftarPW().get(j).getTglBerangkat();
            row[6] = model.getDaftarPW().get(j).getTglPulang();
            tbModel.addRow(row);
            tbViewPW.setRowHeight(j, 20);
        }
        
    }
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJKTG;
    private javax.swing.JButton btnBMM;
    private javax.swing.JButton btnDeletePW;
    private javax.swing.JButton btnDeleteTW;
    private javax.swing.JButton btnEditPW;
    private javax.swing.JButton btnEditTW;
    private javax.swing.JButton btnInputPW;
    private javax.swing.JButton btnInputTG;
    private javax.swing.JButton btnInputTW;
    private javax.swing.JButton btnRefreshCs;
    private javax.swing.JButton btnRefreshRP;
    private javax.swing.JButton btnRefreshTWInputPW;
    private javax.swing.JButton btnSearchDeletePW;
    private javax.swing.JButton btnSearchDeleteTW;
    private javax.swing.JButton btnSearchEditPW;
    private javax.swing.JButton btnSearchEditTW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JList<String> lsTGEditPW;
    private javax.swing.JList<String> lsTGInputPW;
    private javax.swing.JList<String> lsTWEditPW;
    private javax.swing.JList<String> lsTWInputPW;
    private javax.swing.JPanel pCustomer;
    private javax.swing.JPanel pPaketWisata;
    private javax.swing.JPanel pRekapPemesanan;
    private javax.swing.JPanel pTempatWisata;
    private javax.swing.JPanel pTourGuide;
    private javax.swing.JRadioButton rbLakiTG;
    private javax.swing.JRadioButton rbPerempuanTG;
    private javax.swing.JSlider slRatingEditTW;
    private javax.swing.JSlider slRatingInputTW;
    private javax.swing.JScrollPane spTbViewTGTG;
    private javax.swing.JTable tbViewCs;
    private javax.swing.JTable tbViewDeletePW;
    private javax.swing.JTable tbViewDeleteTW;
    private javax.swing.JTable tbViewPW;
    private javax.swing.JTable tbViewRP;
    private javax.swing.JTable tbViewTGTG;
    private javax.swing.JTable tbViewTW;
    private javax.swing.JTextField tfAlamatEditTW;
    private javax.swing.JTextField tfAlamatInputTW;
    private javax.swing.JTextField tfAlamatTG;
    private javax.swing.JTextField tfHargaEditPW;
    private javax.swing.JTextField tfHargaInputPW;
    private javax.swing.JTextField tfIdInputPW;
    private javax.swing.JTextField tfIdInputTW;
    private javax.swing.JTextField tfIdSearchDeletePW;
    private javax.swing.JTextField tfIdSearchDeleteTW;
    private javax.swing.JTextField tfIdSearchEditPW;
    private javax.swing.JTextField tfIdSearchEditTW;
    private javax.swing.JTextField tfIdTG;
    private javax.swing.JTextField tfKontakTG;
    private javax.swing.JTextField tfNamaEditPW;
    private javax.swing.JTextField tfNamaEditTW;
    private javax.swing.JTextField tfNamaInputPW;
    private javax.swing.JTextField tfNamaInputTW;
    private javax.swing.JTextField tfNamaTG;
    private javax.swing.JTextField tfTglBEditPW;
    private javax.swing.JTextField tfTglBInputPW;
    private javax.swing.JTextField tfTglPEditPW;
    private javax.swing.JTextField tfTglPInputPW;
    private javax.swing.JTextField tfUmurTG;
    private javax.swing.JTabbedPane tpAdmin;
    // End of variables declaration//GEN-END:variables
}
