/*
    Edit by Nufus
 */
package tubespbo01;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class GUICustomer extends javax.swing.JFrame {

    /**
     * Creates new form GUICustomer
     */
    private Controller ctrl;
    
    public GUICustomer() {
        initComponents();
        ctrl = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJKReg = new javax.swing.ButtonGroup();
        bgJKUDP = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pRegistrasi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrasiReg = new javax.swing.JButton();
        tfNamaReg = new java.awt.TextField();
        tfUmurReg = new java.awt.TextField();
        tfAlamatReg = new java.awt.TextField();
        rbLakiReg = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbPerempuanReg = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfKontakReg = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfIdReg = new javax.swing.JTextField();
        pPemesanan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfIdPsnPsn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsPaketWisataPsn = new javax.swing.JList<>();
        btnPesanPsn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tfTglPesanPsn = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfIdCsPsn = new javax.swing.JTextField();
        pUbahDataPribadi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdateUDP = new javax.swing.JButton();
        rbLakiUDP = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbPerempuanUDP = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfIdCsUDP = new javax.swing.JTextField();
        btnCariIdCsUDP = new javax.swing.JButton();
        tfNamaUDP = new javax.swing.JTextField();
        tfUmurUDP = new javax.swing.JTextField();
        tfAlamatUDP = new javax.swing.JTextField();
        tfKontakUDP = new javax.swing.JTextField();
        pLihatPaketWisata = new javax.swing.JPanel();
        spTabelLPW = new javax.swing.JScrollPane();
        tbLPW = new javax.swing.JTable();
        pLihatTourGuide = new javax.swing.JPanel();
        spTabelLTG = new javax.swing.JScrollPane();
        tbLTG = new javax.swing.JTable();
        pLihatTempatWisata = new javax.swing.JPanel();
        spTabelLTW = new javax.swing.JScrollPane();
        tbLTW = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu Customer");

        jLabel3.setText("Nama :");

        btnRegistrasiReg.setText("Registrasi");
        btnRegistrasiReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiRegActionPerformed(evt);
            }
        });

        bgJKReg.add(rbLakiReg);
        rbLakiReg.setText("Laki - Laki");
        rbLakiReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiRegActionPerformed(evt);
            }
        });

        jLabel8.setText("Alamat :");

        bgJKReg.add(rbPerempuanReg);
        rbPerempuanReg.setText("Perempuan");
        rbPerempuanReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanRegActionPerformed(evt);
            }
        });

        jLabel9.setText("Kontak :");

        jLabel10.setText("Jenis Kelamin :");

        jLabel11.setText("Umur :");

        jLabel12.setText("ID");

        tfIdReg.setEditable(false);
        tfIdReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRegistrasiLayout = new javax.swing.GroupLayout(pRegistrasi);
        pRegistrasi.setLayout(pRegistrasiLayout);
        pRegistrasiLayout.setHorizontalGroup(
            pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRegistrasiLayout.createSequentialGroup()
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrasiReg)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addContainerGap(489, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRegistrasiLayout.createSequentialGroup()
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfNamaReg, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addGroup(pRegistrasiLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(rbLakiReg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbPerempuanReg))
                                .addComponent(tfIdReg))
                            .addGroup(pRegistrasiLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfUmurReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfKontakReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAlamatReg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(298, 298, 298))))
        );
        pRegistrasiLayout.setVerticalGroup(
            pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistrasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfIdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNamaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRegistrasiLayout.createSequentialGroup()
                        .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rbPerempuanReg)
                            .addComponent(rbLakiReg))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRegistrasiLayout.createSequentialGroup()
                        .addComponent(tfUmurReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAlamatReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfKontakReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrasiReg)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrasi", pRegistrasi);

        jLabel14.setText("Id Pemesanan");

        tfIdPsnPsn.setEditable(false);
        tfIdPsnPsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdPsnPsnActionPerformed(evt);
            }
        });

        jLabel15.setText("Paket Wisata");

        lsPaketWisataPsn.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "paket 1", "paket 2", "paket 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lsPaketWisataPsn);

        btnPesanPsn.setText("Pesan");
        btnPesanPsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanPsnActionPerformed(evt);
            }
        });

        jLabel17.setText("Tanggal Pesan");

        jLabel18.setText("Id Anda");

        tfIdCsPsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdCsPsnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPemesananLayout = new javax.swing.GroupLayout(pPemesanan);
        pPemesanan.setLayout(pPemesananLayout);
        pPemesananLayout.setHorizontalGroup(
            pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesanPsn)
                    .addGroup(pPemesananLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(tfTglPesanPsn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPemesananLayout.createSequentialGroup()
                        .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfIdCsPsn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfIdPsnPsn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        pPemesananLayout.setVerticalGroup(
            pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPemesananLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfIdCsPsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfIdPsnPsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfTglPesanPsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnPesanPsn)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pemesanan", pPemesanan);

        jLabel2.setText("Nama :");

        btnUpdateUDP.setText("Update");
        btnUpdateUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUDPActionPerformed(evt);
            }
        });

        bgJKUDP.add(rbLakiUDP);
        rbLakiUDP.setText("Laki - Laki");
        rbLakiUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiUDPActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat :");

        bgJKUDP.add(rbPerempuanUDP);
        rbPerempuanUDP.setText("Perempuan");
        rbPerempuanUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanUDPActionPerformed(evt);
            }
        });

        jLabel7.setText("Kontak :");

        jLabel4.setText("Jenis Kelamin :");

        jLabel5.setText("Umur :");

        jLabel13.setText("ID :");

        btnCariIdCsUDP.setText("Cari ID");
        btnCariIdCsUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariIdCsUDPActionPerformed(evt);
            }
        });

        tfNamaUDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaUDPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUbahDataPribadiLayout = new javax.swing.GroupLayout(pUbahDataPribadi);
        pUbahDataPribadi.setLayout(pUbahDataPribadiLayout);
        pUbahDataPribadiLayout.setHorizontalGroup(
            pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateUDP)
                    .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                        .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbLakiUDP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPerempuanUDP))
                            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfNamaUDP)
                                    .addComponent(tfIdCsUDP, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnCariIdCsUDP))))
                    .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                        .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUmurUDP)
                            .addComponent(tfAlamatUDP)
                            .addComponent(tfKontakUDP, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        pUbahDataPribadiLayout.setVerticalGroup(
            pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUbahDataPribadiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfIdCsUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariIdCsUDP))
                .addGap(9, 9, 9)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbLakiUDP)
                    .addComponent(rbPerempuanUDP))
                .addGap(11, 11, 11)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfUmurUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfAlamatUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pUbahDataPribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfKontakUDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnUpdateUDP)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ubah Data Pribadi", pUbahDataPribadi);

        tbLPW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Harga", "List Guide", "List Tujuan", "Tgll Berangkat", "Tgl Pulang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTabelLPW.setViewportView(tbLPW);

        javax.swing.GroupLayout pLihatPaketWisataLayout = new javax.swing.GroupLayout(pLihatPaketWisata);
        pLihatPaketWisata.setLayout(pLihatPaketWisataLayout);
        pLihatPaketWisataLayout.setHorizontalGroup(
            pLihatPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatPaketWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLPW, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLihatPaketWisataLayout.setVerticalGroup(
            pLihatPaketWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatPaketWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLPW, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lihat Paket Wisata", pLihatPaketWisata);

        tbLTG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Umur", "Jenis Kelamin", "Alamat", "Kontak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTabelLTG.setViewportView(tbLTG);

        javax.swing.GroupLayout pLihatTourGuideLayout = new javax.swing.GroupLayout(pLihatTourGuide);
        pLihatTourGuide.setLayout(pLihatTourGuideLayout);
        pLihatTourGuideLayout.setHorizontalGroup(
            pLihatTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTourGuideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLTG, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLihatTourGuideLayout.setVerticalGroup(
            pLihatTourGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTourGuideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLTG, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lihat Tour Guide", pLihatTourGuide);

        tbLTW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Alamat", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTabelLTW.setViewportView(tbLTW);

        javax.swing.GroupLayout pLihatTempatWisataLayout = new javax.swing.GroupLayout(pLihatTempatWisata);
        pLihatTempatWisata.setLayout(pLihatTempatWisataLayout);
        pLihatTempatWisataLayout.setHorizontalGroup(
            pLihatTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTempatWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLTW, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLihatTempatWisataLayout.setVerticalGroup(
            pLihatTempatWisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLihatTempatWisataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTabelLTW, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lihat Tempat Wisata", pLihatTempatWisata);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUDPActionPerformed
        // TODO add your handling code here:
        ctrl.updateUDP();
    }//GEN-LAST:event_btnUpdateUDPActionPerformed

    private void rbLakiUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiUDPActionPerformed

    private void rbPerempuanUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanUDPActionPerformed

    private void btnRegistrasiRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiRegActionPerformed
        //if error JOptionPane.showMessageDialog(null, "Hello!");
        ctrl.registReg();
    }//GEN-LAST:event_btnRegistrasiRegActionPerformed

    private void rbLakiRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiRegActionPerformed

    private void rbPerempuanRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanRegActionPerformed

    private void tfIdRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdRegActionPerformed

    private void btnPesanPsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanPsnActionPerformed
        // TODO add your handling code here:
        ctrl.pesanPsn();
    }//GEN-LAST:event_btnPesanPsnActionPerformed

    private void tfIdCsPsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdCsPsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdCsPsnActionPerformed

    private void tfIdPsnPsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdPsnPsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdPsnPsnActionPerformed

    private void btnCariIdCsUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariIdCsUDPActionPerformed
        // TODO add your handling code here:
        ctrl.cariIdCsUDP();
    }//GEN-LAST:event_btnCariIdCsUDPActionPerformed

    private void tfNamaUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaUDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaUDPActionPerformed
    
    //TAB REGISTRASI
    //SETTER
    public void setTfNamaReg (String nama){
        tfNamaReg.setText(nama);
    }
    public void setTfUmurReg (String umur){
        tfUmurReg.setText(umur);
    }
    public void setTfAlamatReg (String alamat){
        tfAlamatReg.setText(alamat);
    }
    public void setTfKontakReg (String kontak){
        tfKontakReg.setText(kontak);
    }
    //GETTER
    public JTextField getTfIdReg (){
        return tfIdReg;
    }
    public String getTfNamaReg (){
        return tfNamaReg.getText();
    }
    public String getRbJKReg(){
        if(rbLakiReg.isSelected()){
            return "Laki-Laki";
        }else{
            return "Perempuan";
        }
    }
    public String getTfUmurReg (){
        return tfUmurReg.getText();
    }
    public String getTfAlamatReg (){
        return tfAlamatReg.getText();
    }
    public String getTfKontakReg (){
        return tfKontakReg.getText();
    }
    public void resetViewReg(){
        tfIdReg.setText("C-"+Customer.getSidC());
        tfNamaReg.setText("");
        bgJKReg.clearSelection();
        tfUmurReg.setText("");
        tfAlamatReg.setText("");
        tfKontakReg.setText("");
    }
    
    //TAB PEMESANAN
    //SETTER
    public void setLsPaketWisataPsn (String[] list){
        lsPaketWisataPsn.setListData(list);
    }
    public void setTfTgllPesanPsn(String tglPesan){
        tfTglPesanPsn.setText(tglPesan);
    }
    //GETTER
    public String getTfIdCsPsn(){
        return tfIdCsPsn.getText();
    }
    public JTextField getTfIdPsnPsn (){
        return tfIdPsnPsn;
    }
    public JList<String> getLsPaketWisataPsn (){
        return lsPaketWisataPsn;
    }
    public String getTfTglPesanPsn(){
        return tfTglPesanPsn.getText();
    }
    public void resetViewPsn(){
        tfIdCsPsn.setText("");
        tfIdPsnPsn.setText("P-"+Pemesanan.getSidP());
        lsPaketWisataPsn.clearSelection();
        tfTglPesanPsn.setText("");
    }

    
    //TAB UBAH DATA PRIBADI
    //SETTER
    public void setTfIdCsUDP (String id){
        tfIdCsUDP.setText("C-"+id);
    }
    public void setTfNamaUDP (String nama){
        tfNamaUDP.setText(nama);
    }
    public void setTfUmurUDP (String umur){
        tfUmurUDP.setText(umur);
    }
    public void setTfAlamatUDP (String alamat){
        tfAlamatUDP.setText(alamat);
    }
    public void setTfKontakUDP (String kontak){
        tfKontakUDP.setText(kontak);
    }
    //GETTER

    public String getTfIdCsUDP (){
        return tfIdCsUDP.getText();
    }
    public JTextField getTfNamaUDP (){
        return tfNamaUDP;
    }
    public JRadioButton getRbLakiUDP(){
        return rbLakiUDP;
    }
    public JRadioButton getRbPerempuanUDP(){
        return rbPerempuanUDP;
    }
    public ButtonGroup getBgJKUDP(){
        return bgJKUDP;
    }
    public JTextField getTfUmurUDP (){
        return tfUmurUDP;
    }
    public JTextField getTfAlamatUDP (){
        return tfAlamatUDP;
    }
    public JTextField getTfKontakUDP (){
        return tfKontakUDP;
    }
    public void resetViewUDP(){
        tfIdCsUDP.setText("");
        tfNamaUDP.setText("");
        bgJKUDP.clearSelection();
        tfUmurUDP.setText("");
        tfAlamatUDP.setText("");
        tfKontakUDP.setText("");
    }
    
    //TAB LIHAT PAKET WISATA
    //SETTER
    public void setTbLPW (String[] list){
        
    }
    //GETTER
    public List getTbLPW (){
        return null;
    }
    
    //TAB LIHAT TOUR GUIDE
    //SETTER
    public void setTbLTG (String[] list){
        
    }
    //GETTER
    public List getTbLTG (){
        return null;
    }
    
    //TAB LIHAT TEMPAT WISATA
    //SETTER
    public void setTbLTW (String[] list){
        
    }
    //GETTER
    public List getTbLTW (){
        return null;
    }
    
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(GUICustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new GUICustomer().setVisible(true);
        }
    });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJKReg;
    private javax.swing.ButtonGroup bgJKUDP;
    private javax.swing.JButton btnCariIdCsUDP;
    private javax.swing.JButton btnPesanPsn;
    private javax.swing.JButton btnRegistrasiReg;
    private javax.swing.JButton btnUpdateUDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lsPaketWisataPsn;
    private javax.swing.JPanel pLihatPaketWisata;
    private javax.swing.JPanel pLihatTempatWisata;
    private javax.swing.JPanel pLihatTourGuide;
    private javax.swing.JPanel pPemesanan;
    private javax.swing.JPanel pRegistrasi;
    private javax.swing.JPanel pUbahDataPribadi;
    private javax.swing.JRadioButton rbLakiReg;
    private javax.swing.JRadioButton rbLakiUDP;
    private javax.swing.JRadioButton rbPerempuanReg;
    private javax.swing.JRadioButton rbPerempuanUDP;
    private javax.swing.JScrollPane spTabelLPW;
    private javax.swing.JScrollPane spTabelLTG;
    private javax.swing.JScrollPane spTabelLTW;
    private javax.swing.JTable tbLPW;
    private javax.swing.JTable tbLTG;
    private javax.swing.JTable tbLTW;
    private java.awt.TextField tfAlamatReg;
    private javax.swing.JTextField tfAlamatUDP;
    private javax.swing.JTextField tfIdCsPsn;
    private javax.swing.JTextField tfIdCsUDP;
    private javax.swing.JTextField tfIdPsnPsn;
    private javax.swing.JTextField tfIdReg;
    private java.awt.TextField tfKontakReg;
    private javax.swing.JTextField tfKontakUDP;
    private java.awt.TextField tfNamaReg;
    private javax.swing.JTextField tfNamaUDP;
    private javax.swing.JTextField tfTglPesanPsn;
    private java.awt.TextField tfUmurReg;
    private javax.swing.JTextField tfUmurUDP;
    // End of variables declaration//GEN-END:variables
}
